<a href="https://colab.research.google.com/github/66AbiyyuM66/Pemerograman-Dasar/blob/main/ATS_Kelompok_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ASESMEN TENGAH SEMSTER (ATS)**
Mengerjakan Soal Genap -> 2, 4, 6, 8, 10 Beserta Challenge

ANGGOTA KELOMPOK 5 :

1. Daniel Christian Sitanggang - 4232401040
2. Aldino Eka Putra - 4232401049
3. Abiyyu Muflih Kurnia - 42232401041

In [9]:
print("=== Soal 2 ===\n")

# Program Menghitung Efisiensi Turbin
def hitung_efisiensi(input_energi, output_energi):
    """ Fungsi untuk menghitung efisiensi turbin. """

    efisiensi = output_energi / input_energi
    return efisiensi

# Menghitung efisiensi
hasil = hitung_efisiensi(500, 400)

# Hasil
print("Program Menghitung Efisiensi Turbin")
print(f"Input Energi   = {input_energi} Joule")
print(f"Output Energi  = {output_energi} Joule")
print(f"Efisiensi      = {hasil * 100}%")


=== Soal 2 ===

Program Menghitung Efisiensi Turbin
Input Energi   = 500 Joule
Output Energi  = 400 Joule
Efisiensi      = 80.0%


Ini adalah fungsi untuk menghitung efisiensi Turbin, nama fungsinya adalah hitung_efisiensi dan memiliki parameter input_energi dan output energi, setelah itu di buat tujuan fungsi didalam definisi, dan memasukkan rumus untuk menghitung efisiensi diletakkan dalam variabel efisiensi, dan buat juga pengoperasian untuk hasilnya,.Untuk memanggil fungsi tersebut, cukup memberikan dua nilai yaitu input energi sebesar 500 dan output energi sebesar 400 sebagai parameter. Pemanggilan dilakukan dengan membuat beberapa code print untuk setiap hasilnya. Hasilnya akan menghitung perbandingan antara output dan input energi, yaitu 400 dibagi 500, sehingga diperoleh nilai efisiensi sebesar 80%.


In [12]:
print("=== Soal 4 ====\n")

# Program Logika Katup Pengaman
tekanan_uap = 150.0
status_manual_override = False

# Rumus Logika dan Penentuan Hasil
if tekanan_uap > 140 and status_manual_override == False:
    hasil = "Katup Terbuka"
else:
    hasil = "Katup Tertutup"

# Hasil
print("Status Katup Pengaman")
print(f"Tekanan Uap  = {tekanan_uap} psi")
print(f"Manual Override = {status_manual_override}")
print(f"Status Katup = {hasil}")

=== Soal 4 ====

Status Katup Pengaman
Tekanan Uap  = 150.0 psi
Manual Override = False
Status Katup = Katup Terbuka


Ini adalah program Katup Pengaman Program menggunakan logika if majemuk(if dan else) dengan operator and. Katup hanya terbuka jika kedua syarat berikut terpenuhi yaitu Tekanan Uap (150.0 Psi) lebih besar dari 140. (Benar) dan Kontrol Manual sama dengan False. (Benar) Karena kedua syarat BENAR yang di sebabkan oleh operator and yang dimana harus kedua kondisi True baru kondisi if bisa jalan, perintah if dijalankan, dan status katup menjadi "Katup Terbuka". Untuk Pemanggilan hasil di buat 4 code print yang memanpilkan Judul, tekanan uap, manual override, dan status katup

In [13]:
print("=== Soal 6 ===\n")

# Program Menghitung Daya Listrik dari Generator
tegangan = 220
arus = 15

# Rumus Daya
daya = tegangan * arus

# Hasil
print("Program Menghitung Daya Listrik")
print(f"Tegangan (V) = {tegangan} Volt")
print(f"Arus (I)     = {arus} Ampere")
print(f"Daya (P)     = {daya} Watt")


=== Soal 6 ===

Program Menghitung Daya Listrik
Tegangan (V) = 220 Volt
Arus (I)     = 15 Ampere
Daya (P)     = 3300 Watt


Ini adalah Program untuk menghitung daya listrik yang di hasilkan generator (dari soal) di program ini, terdapat dua variabel yaitu tegangan = 220 dan arus = 15 serta menggunakan rumus dasar listrik P = V × I, di mana tegangan (V) dikalikan dengan arus (I) untuk mendapatkan hasil daya (P) dalam satuan Watt ini tersimpan di variabel daya. Jadi, dengan tegangan 220 V dan arus 15 A, daya yang dihasilkan adalah 3300 Watt. Untuk pemanggilan hasil di buat 4 kode print dimana itu judul, Tegangan, Arus dan DAya hasil perhitungan.

In [14]:
print("=== Soal 8 ===")

# Program Menghitung Efisiensi Termal Turbin Gas
def hitung_efisiensi_termal():
    """Fungsi untuk menghitung efisiensi termal turbin gas."""

    print("=== Program Menghitung Efisiensi Termal Turbin Gas ===")

    energi_masuk = float(input("Masukkan energi masuk (Joule): "))
    energi_keluar = float(input("Masukkan energi keluar (Joule): "))

    # Rumus
    efisiensi = (energi_keluar / energi_masuk) * 100

    # Hasil
    print(f"\nEfisiensi Termal Turbin Gas = {efisiensi:.2f}%")

hitung_efisiensi_termal()


=== Soal 8 ===
=== Program Menghitung Efisiensi Termal Turbin Gas ===
Masukkan energi masuk (Joule): 200
Masukkan energi keluar (Joule): 100

Efisiensi Termal Turbin Gas = 50.00%


Ini adalah Program untuk menghitung persentase Efisiensi termal turbin gas, program ini menggunakan fungsi bernama hitung_efisiensi_termal() dan menambahkan tujuan dari fungsi ini dengan simbol (""" """), kami disini untuk mendapatkan energi masuk dan keluar menggunakan metode input(), agar bisa menerima inputan dari user disini untuk memisahkan logika perhitungan dari program utama (modularisasi). Pengguna memasukkan nilai energi masuk dan energi keluar, lalu program menghitung efisiensi dengan rumus Efisiensi=Energi Masuk / Energi Keluar​×100. Untuk hasil di buat satu kode print untuk menampilkan efisiensi termalnya dan memanggil fungsi dengan mengetikkan nama dari fungsi yaitu hitung_efisiensi_termal. Hasil akhirnya ditampilkan dalam persentase efisiensi termal.


In [15]:
print("=== Soal 10 ===\n")

# Program Pengisian Tangki Bahan Bakar
bahan_bakar = 0
kapasitas_tangki = 100

# Peoses Pengisian
while bahan_bakar <= kapasitas_tangki :
  print(f"Mengisi bahan bakar sebanyak {bahan_bakar} liter")

  if bahan_bakar == 80 :
    print(f"WARNING: Hampir Penuh!")
  elif bahan_bakar == kapasitas_tangki:
    print(f"TANGKI PENUH - Pengisian Berhenti!")
    break

  bahan_bakar += 10

=== Soal 10 ===

Mengisi bahan bakar sebanyak 0 liter
Mengisi bahan bakar sebanyak 10 liter
Mengisi bahan bakar sebanyak 20 liter
Mengisi bahan bakar sebanyak 30 liter
Mengisi bahan bakar sebanyak 40 liter
Mengisi bahan bakar sebanyak 50 liter
Mengisi bahan bakar sebanyak 60 liter
Mengisi bahan bakar sebanyak 70 liter
Mengisi bahan bakar sebanyak 80 liter
Mengisi bahan bakar sebanyak 90 liter
Mengisi bahan bakar sebanyak 100 liter
TANGKI PENUH - Pengisian Berhenti!


Ini adalah Program untuk menampilkan simulasi proses pengisian bahan bakar hingga penuh dengan menggunakan gabungan antara perulangan While dan logika percabangan if dan elif, disini memiliki dua variabel yaitu bahan_bakar sebagai nilai dari awal tangki dan kapasitas_tangki adalah maksimal dari bahan bakar yang bisa di tampung, untuk proses pengisian bisa di gunakan while, ketika bahan bakarnya lebih kecil atau sama dengan kapasitas tanfki maka ini akan loop sampai bahan bakarnya sama dengan kapasitas baru dia berhenti, untuk logika if disini menambah kan kondisi peringatan atau pemberitahuan ketika bahan bakar sudah terisi 80 maka muncul (Warning), dan di printkan untuk memanggil pemberitahuan, lalu elif untuk peringatan bahwa tangki sudah penuh, di panggil menggunakan print dan muncul (Tangki penuh), lalu ketika sudah penuh gunakan intruksi break agar loopnya berhenti di kondisi tersebut, lalu ada pengoperaasian dimana setiap iterasi penambahan bahan bakar sebanyak 10 liter.

In [32]:
print("=== Soal Challange ===")

# Program: Simulasi Kinerja Panel Surya (PLTS)
# Fungsi Menghitung Energi Harian
def energi_harian(daya_panel_kw, jam_matahari, efisiensi):
    """Menghitung energi harian (kWh)"""

    return daya_panel_kw * jam_matahari * efisiensi

# Fungsi Efisiensi Berdasarkan Faktor Cuaca
def kategori_cuaca(kondisi):
    """Mengembalikan faktor efisiensi berdasarkan kondisi cuaca"""

    if kondisi.lower() == "cerah":
        return 1.0
    elif kondisi.lower() == "berawan":
        return 0.7
    elif kondisi.lower() == "mendung":
        return 0.4
    elif kondisi.lower() == "hujan":
        return 0.2
    elif kondisi.lower() == "badai":
        return 0.05
    else:
        return 0.5

# Fungsi Menentukan Kategori Energi
def kategori_produksi(energi):
    """Menentukan kategori hasil energi."""
    if energi < 10:
        return "Rendah"
    elif energi < 50:
        return "Sedang"
    else:
        return "Tinggi"

# Simulasi
print("\n=== SIMULASI PRODUKSI ENERGI PANEL SURYA ===\n")

jumlah_hari = int(input("Masukkan jumlah hari simulasi: "))
daya_panel_kw = float(input("Masukkan total daya panel (kW): "))

total_energi = 0

for hari in range(1, jumlah_hari + 1):
    print(f"\nHari ke-{hari}:")
    kondisi = input("Masukkan kondisi cuaca (cerah/berawan/mendung/hujan/badai): ")
    jam_matahari = float(input("Masukkan jam penyinaran matahari efektif: "))

    efisiensi_cuaca = kategori_cuaca(kondisi)
    energi = energi_harian(daya_panel_kw, jam_matahari, efisiensi_cuaca)
    total_energi += energi

    print(f"Efisiensi berdasarkan cuaca: {efisiensi_cuaca*100:.1f}%")
    print(f"Energi harian: {energi:.2f} kWh ({kategori_produksi(energi)})")

# Target Energi
target = 300
hari_ke = 1
produksi = total_energi

print("\n=== PERKIRAAN CAPAIAN TARGET ENERGI ===")
while produksi < target:
    produksi += (total_energi / jumlah_hari)
    hari_ke += 1
    print(f"Hari ke-{hari_ke}: total kumulatif {produksi:.2f} kWh")

print(f"Target tercapai setelah hari ke-{hari_ke}")

print("\n=== HASIL AKHIR ===")
print(f"Total energi selama {jumlah_hari} hari: {total_energi:.2f} kWh")
print(f"Rata-rata per hari: {total_energi/jumlah_hari:.2f} kWh")
print("Simulasi telah selesai ")


=== Soal Challange ===

=== SIMULASI PRODUKSI ENERGI PANEL SURYA ===

Masukkan jumlah hari simulasi: 2
Masukkan total daya panel (kW): 50

Hari ke-1:
Masukkan kondisi cuaca (cerah/berawan/mendung/hujan/badai): berawan
Masukkan jam penyinaran matahari efektif: 3
Efisiensi berdasarkan cuaca: 70.0%
Energi harian: 105.00 kWh (Tinggi)

Hari ke-2:
Masukkan kondisi cuaca (cerah/berawan/mendung/hujan/badai): hujan
Masukkan jam penyinaran matahari efektif: 1
Efisiensi berdasarkan cuaca: 20.0%
Energi harian: 10.00 kWh (Sedang)

=== PERKIRAAN CAPAIAN TARGET ENERGI ===
Hari ke-2: total kumulatif 172.50 kWh
Hari ke-3: total kumulatif 230.00 kWh
Hari ke-4: total kumulatif 287.50 kWh
Hari ke-5: total kumulatif 345.00 kWh
Target tercapai setelah hari ke-5

=== HASIL AKHIR ===
Total energi selama 2 hari: 115.00 kWh
Rata-rata per hari: 57.50 kWh
Simulasi telah selesai 


Ini adalah program untuk simulasi kinerja Pembangkit Listrik Tenaga Surya (PLTS)
yang di mana program inni mencakup hasil simulasi berapa hari yang di inginkan dan pengaruh faktor cuaca juga, lalu ada perkiraan tercapainya target energi berapa KWh dan berapa hari, serta  menampilkan selama sehari simulasi berapa persentase efisiensi pembangkit dan energi harian, disini kami memilih program ini karna berkaitan langsung dengan RPE, yang dimana ini permasalahan atau case yang akan sering ditemukan, salam program ini  kami menggunakan berbagai kombinasi fungsi, if, elif, else, while, dan for serta beberapa metode lainnya terdiri dari 3 fungsi yaitu energi_harian yang parameternya daya_panel_kw, jam_matahari dan efisiensi yang berguna untuk menghitung energi harian, yang kedua ada fungsi kategori_cuaca dengan parameter(kondisi), dimana ini menggunakan percabangan logika if, elif dan else untuk menentukan efisiensi pembangkit ketika berada di kondisi cuaca yang berbeda, untuk yang ketiga fungsi ketegori_produksi yang parameternya adalah energi ini juga menggunakan percabangan logika if, elif, dan else untuk menentukan kondisi apakah produks energinya rendah atau sedang atau tinggi, lalu ada ke bagian simulasi yang berfungsi untuk menambaah kan beberapa variable dari yang di butuhkan, untuk variabel jumlah_hari dan daya_panel_kw kami menggunakan fungsi input() agar lebih fleksibel ketika di gunakan, dilanjutkan dengan perulangan for dan while untuk menentukan perulangan, untuk for dan while menentukan proses dari hari ke 1 hingga mencapai target yang kami buat yaitu 300 kWh, dan beberapa kode print()
untuk menampilkan hasilnya, untuk di kasus ini kami mencoba simulasi selama 2 hari dengan daya panel 50 kW, kondisi di hari perama berawan, dan kondisi di hari kedua hujan yang dapat memengaruhi produksi harian karena kurangnya jam penyinaran matahari efektif, setelah semua hasil akhirnya adalah total energi selama 2 hari, rata rata energi per hari, dan simulasi sudah selesai

